/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AlbumStore } from "./AlbumStore";
export * as factories from "./factories";
export { AlbumStore__factory } from "./factories/AlbumStore__factory";
